[aws]
ankita-app-server ansible_host=54.82.46.233 ansible_user=ubuntu ansible_ssh_private_key_file=~/ankita-new-key.pem

[azure]
azure-vm ansible_host=168.62.59.194 ansible_user=azureuser ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519 ansible_python_interpreter=/usr/bin/python3
